//clear signIn data
export const CLEAR_SIGN_IN_DATA = "CLEAR_SIGN_IN_DATA"
//clear signOut data
export const CLEAR_SIGN_OUT_DATA = "CLEAR_SIGN_OUT_DATA"
//signup
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_REQUEST_FAIL = "SIGN_UP_REQUEST_FAIL"
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS"
//signin
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_REQUEST_FAIL = "SIGN_IN_REQUEST_FAIL"
export const SIGN_IN_REQUEST_SUCCESS = "SIGN_IN_REQUEST_SUCCESS"
//signout
export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST"
export const SIGN_OUT_REQUEST_FAIL = "SIGN_OUT_REQUEST_FAIL"
export const SIGN_OUT_REQUEST_SUCCESS = "SIGN_OUT_REQUEST_SUCCESS"
//category
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST"
export const CREATE_CATEGORY_REQUEST_FAIL = "CREATE_CATEGORY_REQUEST_FAIL"
export const FETCH_CATEGORIES_REQUEST_FAIL = "FETCH_CATEGORIES_REQUEST_FAIL"
export const UPDATE_SINGLE_CATEGORY_REQUEST = "UPDATE_SINGLE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_REQUEST_SUCCESS = "CREATE_CATEGORY_REQUEST_SUCCESS"
export const FETCH_CATEGORIES_REQUEST_SUCCESS = "FETCH_CATEGORIES_REQUEST_SUCCESS"
export const UPDATE_SINGLE_CATEGORY_REQUEST_FAIL = "UPDATE_SINGLE_CATEGORY_REQUEST_FAIL"
export const UPDATE_SINGLE_CATEGORY_REQUEST_SUCCESS = "UPDATE_SINGLE_CATEGORY_REQUEST_SUCCESS"
//Film
export const GET_FILMS_REQUEST = "GET_FILMS_REQUEST"
export const CREATE_FILM_REQUEST = "CREATE_FILM_REQUEST"
export const GET_FILMS_REQUEST_FAIL = "GET_FILMS_REQUEST_FAIL"
export const CREATE_FILM_REQUEST_FAIL = "CREATE_FILM_REQUEST_FAIL"
export const GET_FILMS_REQUEST_SUCCESS = "GET_FILMS_REQUEST_SUCCESS"
export const CREATE_FILM_REQUEST_SUCCESS = "CREATE_FILM_REQUEST_SUCCESS"
export const DELETE_SINGLE_FILM_REQUEST = "DELETE_SINGLE_FILM_REQUEST"
export const UPDATE_SINGLE_FILM_REQUEST = "UPDATE_SINGLE_FILM_REQUEST"
export const DELETE_SINGLE_FILM_REQUEST_FAIL = "DELETE_SINGLE_FILM_REQUEST_FAIL"
export const UPDATE_SINGLE_FILM_REQUEST_FAIL = "UPDATE_SINGLE_FILM_REQUEST_FAIL"
export const DELETE_SINGLE_FILM_REQUEST_SUCCESS = "DELETE_SINGLE_FILM_REQUEST_SUCCESS"
export const UPDATE_SINGLE_FILM_REQUEST_SUCCESS = "UPDATE_SINGLE_FILM_REQUEST_SUCCESS"